# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoguiApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoguiApp
  pod 'RealmSwift'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'

  target 'DoguiAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoguiAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
